// --- Simple i18n dictionary ---
export const DICT = {
  en: {
    appTitle: "Saxion Intake – Proof of Concept",
    welcome: "Welcome",
    chooseUser: "Choose a demo user",
    email: "Email",
    password: "Password",
    login: "Login",
    logout: "Logout",
    start: "Start",
    resume: "Resume",
    applications: "Applications",
    archives: "Archives (older than 2 years)",
    runArchival: "Run archival now",
    downloadData: "Download JSON",
    privacy: "Privacy Policy",
    language: "Language",
    local: "Local",
    international: "International",
    program: "Programme",
    cycle: "Cycle",
    status: "Status",
    created: "Created",
    archived: "Archived",
    inProgress: "In progress",
    new: "New",
    submitted: "Submitted",
    resultPublished: "Result published",
    uploadDocuments: "Upload Documents",
    assignment: "Assignment",
    appointment: "Appointment",
    interview: "Interview",
    result: "Result",
    docHint: "Upload study‑related documents (passport, diploma, transcript).",
    upload: "Upload",
    noDocs: "No documents yet.",
    yourDocs: "Your documents",
    submitAssignment: "Submit assignment",
    assignmentHint: "Paste your motivation or upload a PDF.",
    selectDate: "Select date",
    selectTime: "Select time",
    meetingType: "Meeting type",
    intake: "Intake",
    meetGreet: "Meet & Greet",
    notes: "Notes",
    save: "Save",
    interviewMode: "Interview mode",
    online: "Online",
    onCampus: "On campus",
    videoLink: "Video link",
    publishResult: "Publish result",
    unpublishResult: "Unpublish result",
    decision: "Decision",
    admit: "Admit",
    conditional: "Conditional",
    reject: "Reject",
    publishedAt: "Published at",
    noResult: "No published result yet.",
    markAllDone: "Mark steps complete",
    back: "Back",
    startOrResume: "Start / Resume",
    multiApplicationsNote:
      "You can maintain multiple applications; use Start/Resume to continue.",
    profile: "Profile",
    manageYourProfile: "Manage your profile information",
    personalInformation: "Personal Information",
    fullName: "Full Name",
    enterFullName: "Enter your full name",
    enterEmail: "Enter your email address",
    role: "Role",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    applicationStatistics: "Application Statistics",
    totalApplications: "Total Applications",
    completedApplications: "Completed Applications",
    inProgressApplications: "In Progress Applications",
    locationOfHome: "Location of Home",
    enterLocationOfHome: "Enter your home location",
    dateOfBirth: "Date of Birth",
    enterDateOfBirth: "Enter your date of birth",
    profileIncomplete: "Profile Incomplete",
    completeProfileFirst: "You first need to complete your profile before doing something else.",
    completeProfile: "Complete Profile",
    notSpecified: "Not specified",
    upcomingAppointments: "Upcoming Appointments",
    noUpcomingAppointments: "No upcoming appointments",
    viewApplication: "View",
    joinMeeting: "Join",
    // New ApplicationView translations
    questionnaire: "Questionnaire",
    completeQuestionnaire: "Complete Questionnaire",
    questionnaireCompleted: "Questionnaire completed on",
    writeMotivationLetter: "Write your motivation letter here...",
    completeQuestionnaireToProceed: "Complete the application questionnaire to proceed",
    documentsUnderReview: "Documents Under Review",
    documentsUnderReviewDescription: "Our team is reviewing your uploaded documents. This usually takes a few minutes.",
    documentsApproved: "Documents Approved!",
    documentsApprovedDescription: "Your documents have been reviewed and approved. You can now proceed to schedule appointments.",
    scheduleAppointments: "Schedule Appointments",
    scheduleAppointmentsDescription: "Schedule your intake appointment and interview",
    appointmentsLocked: "Appointments Locked",
    appointmentsLockedDescription: "You need to complete the previous steps and get document approval before scheduling appointments.",
    backToDocuments: "Back to Documents",
    proceedToAppointments: "Proceed to Appointments",
    waitingForApproval: "Waiting for Approval...",
    saveAppointment: "Save Appointment",
    additionalNotes: "Additional notes...",
    noDocumentsUploadedYet: "No documents uploaded yet",
    yourDocuments: "Your Documents",
    uploadRequiredDocuments: "Upload your required documents",
  },
  nl: {
    appTitle: "Saxion Intake – Proof of Concept",
    welcome: "Welkom",
    chooseUser: "Kies een demo‑gebruiker",
    email: "E‑mail",
    password: "Wachtwoord",
    login: "Inloggen",
    logout: "Uitloggen",
    start: "Start",
    resume: "Hervatten",
    applications: "Aanvragen",
    archives: "Archief (ouder dan 2 jaar)",
    runArchival: "Archivering uitvoeren",
    downloadData: "JSON downloaden",
    privacy: "Privacyverklaring",
    language: "Taal",
    local: "Nationaal",
    international: "Internationaal",
    program: "Opleiding",
    cycle: "Cohort",
    status: "Status",
    created: "Aangemaakt",
    archived: "Gearchiveerd",
    inProgress: "Bezig",
    new: "Nieuw",
    submitted: "Ingediend",
    resultPublished: "Resultaat gepubliceerd",
    uploadDocuments: "Documenten uploaden",
    assignment: "Opdracht",
    appointment: "Afspraak",
    interview: "Interview",
    result: "Resultaat",
    docHint: "Upload studie‑documenten (paspoort, diploma, cijferlijst).",
    upload: "Uploaden",
    noDocs: "Nog geen documenten.",
    yourDocs: "Jouw documenten",
    submitAssignment: "Opdracht indienen",
    assignmentHint: "Plak je motivatie of upload een PDF.",
    selectDate: "Kies datum",
    selectTime: "Kies tijd",
    meetingType: "Afspraaktype",
    intake: "Intake",
    meetGreet: "Meet & Greet",
    notes: "Notities",
    save: "Opslaan",
    interviewMode: "Interviewmodus",
    online: "Online",
    onCampus: "Op locatie",
    videoLink: "Videolink",
    publishResult: "Resultaat publiceren",
    unpublishResult: "Publicatie ongedaan maken",
    decision: "Beslissing",
    admit: "Toelaten",
    conditional: "Voorwaardelijk",
    reject: "Afwijzen",
    publishedAt: "Gepubliceerd op",
    noResult: "Nog geen gepubliceerd resultaat.",
    markAllDone: "Markeer stappen als voltooid",
    back: "Terug",
    startOrResume: "Start / Hervat",
    multiApplicationsNote:
      "Je kunt meerdere aanvragen beheren; gebruik Start/Hervat om verder te gaan.",
    profile: "Profiel",
    manageYourProfile: "Beheer je profielinformatie",
    personalInformation: "Persoonlijke Informatie",
    fullName: "Volledige Naam",
    enterFullName: "Voer je volledige naam in",
    enterEmail: "Voer je e-mailadres in",
    role: "Rol",
    editProfile: "Profiel Bewerken",
    saveChanges: "Wijzigingen Opslaan",
    cancel: "Annuleren",
    applicationStatistics: "Aanvraagstatistieken",
    totalApplications: "Totaal Aanvragen",
    completedApplications: "Voltooide Aanvragen",
    inProgressApplications: "Aanvragen in Uitvoering",
    locationOfHome: "Locatie van Thuis",
    enterLocationOfHome: "Voer je thuislocatie in",
    dateOfBirth: "Geboortedatum",
    enterDateOfBirth: "Voer je geboortedatum in",
    profileIncomplete: "Profiel Onvolledig",
    completeProfileFirst: "Je moet eerst je profiel voltooien voordat je iets anders kunt doen.",
    completeProfile: "Profiel Voltooien",
    notSpecified: "Niet opgegeven",
    upcomingAppointments: "Aankomende Afspraken",
    noUpcomingAppointments: "Geen aankomende afspraken",
    viewApplication: "Bekijk",
    joinMeeting: "Deelnemen",
    // New ApplicationView translations
    questionnaire: "Vragenlijst",
    completeQuestionnaire: "Vragenlijst Voltooien",
    questionnaireCompleted: "Vragenlijst voltooid op",
    writeMotivationLetter: "Schrijf hier je motivatiebrief...",
    completeQuestionnaireToProceed: "Voltooi de aanvraagvragenlijst om door te gaan",
    documentsUnderReview: "Documenten in Beoordeling",
    documentsUnderReviewDescription: "Ons team beoordeelt je geüploade documenten. Dit duurt meestal een paar minuten.",
    documentsApproved: "Documenten Goedgekeurd!",
    documentsApprovedDescription: "Je documenten zijn beoordeeld en goedgekeurd. Je kunt nu doorgaan met het plannen van afspraken.",
    scheduleAppointments: "Afspraken Plannen",
    scheduleAppointmentsDescription: "Plan je intake afspraak en interview",
    appointmentsLocked: "Afspraken Vergrendeld",
    appointmentsLockedDescription: "Je moet eerst de vorige stappen voltooien en documentgoedkeuring krijgen voordat je afspraken kunt plannen.",
    backToDocuments: "Terug naar Documenten",
    proceedToAppointments: "Doorgaan naar Afspraken",
    waitingForApproval: "Wachten op Goedkeuring...",
    saveAppointment: "Afspraak Opslaan",
    additionalNotes: "Aanvullende notities...",
    noDocumentsUploadedYet: "Nog geen documenten geüpload",
    yourDocuments: "Jouw Documenten",
    uploadRequiredDocuments: "Upload je vereiste documenten",
  },
};

// --- Demo JSON data bootstrap ---
export const DEMO_JSON = {
  users: [
    {
      id: "u1",
      name: "Alex Jansen",
      email: "alex@saxion-demo.nl",
      password: "demo",
      role: "student",
      locale: "en", // Changed to English as default
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-nl-2023",
          program: "HBO-ICT",
          cycle: "2023/2024",
          createdAt: "2023-05-20",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-01-15", time: "14:00", type: "intake", notes: "Initial intake meeting" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-old-2021",
          program: "Creative Media",
          cycle: "2021/2022",
          createdAt: "2021-03-10",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [
              {
                id: "d1",
                label: "Diploma.pdf",
                filename: "Diploma.pdf",
                size: 120000,
                mime: "application/pdf",
                uploadedAt: "2021-03-12",
              },
            ],
            assignment: {
              text: "Portfolio link included.",
              file: null,
              submittedAt: "2021-03-15",
            },
            appointment: {
              date: "2021-03-20",
              time: "10:00",
              type: "intake",
              notes: "",
            },
            interview: {
              date: "2021-03-25",
              time: "09:30",
              mode: "online",
              link: "https://meet.example/abc",
            },
            result: {
              published: true,
              decision: "admit",
              publishedAt: "2021-04-10",
              notes: "Congrats!",
            },
          },
        },
        {
          id: "app-nl-2025",
          program: "Business Administration",
          cycle: "2025/2026",
          createdAt: "2024-12-15",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-01-18", time: "16:00", type: "intake", notes: "Business program intake interview" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u2",
      name: "Chidinma Okoro",
      email: "chidinma@saxion-demo.ng",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-int-2025",
          program: "Applied Computer Science (English)",
          cycle: "2025/2026",
          createdAt: "2025-06-01",
          status: "new",
          isInternational: true,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-01-20", time: "10:30", type: "meet&greet", notes: "International student meet & greet session" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u3",
      name: "Staff Demo",
      email: "staff@saxion-demo.edu",
      password: "demo",
      role: "staff",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [],
    },
    {
      id: "u4",
      name: "Emma de Vries",
      email: "test1@saxion.nl",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-test1-2025-1",
          program: "International Business Management",
          cycle: "2025/2026",
          createdAt: "2024-11-15",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-01-22", time: "09:00", type: "intake", notes: "Business management intake" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-test1-2025-2",
          program: "Marketing",
          cycle: "2025/2026",
          createdAt: "2024-12-01",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-01-25", time: "11:30", type: "intake", notes: "Marketing program assessment" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u5",
      name: "Lars van Berg",
      email: "test2@saxion.nl",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-test2-2025-1",
          program: "Mechanical Engineering",
          cycle: "2025/2026",
          createdAt: "2024-10-20",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-01-28", time: "13:00", type: "intake", notes: "Engineering program evaluation" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-test2-2025-2",
          program: "Industrial Design",
          cycle: "2025/2026",
          createdAt: "2024-11-30",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-03", time: "15:30", type: "intake", notes: "Design portfolio review" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u6",
      name: "Sophie Bakker",
      email: "test3@saxion.nl",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-test3-2025-1",
          program: "Psychology",
          cycle: "2025/2026",
          createdAt: "2024-09-15",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-05", time: "10:00", type: "intake", notes: "Psychology program interview" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-test3-2025-2",
          program: "Social Work",
          cycle: "2025/2026",
          createdAt: "2024-10-05",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-08", time: "14:30", type: "intake", notes: "Social work motivation interview" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u7",
      name: "Thijs Hendriks",
      email: "test4@saxion.nl",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-test4-2025-1",
          program: "Game Design & Development",
          cycle: "2025/2026",
          createdAt: "2024-08-20",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-10", time: "09:30", type: "intake", notes: "Game development portfolio assessment" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-test4-2025-2",
          program: "Media Technology",
          cycle: "2025/2026",
          createdAt: "2024-09-30",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-12", time: "16:00", type: "intake", notes: "Media technology skills evaluation" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u8",
      name: "Lisa Dijkstra",
      email: "test5@saxion.nl",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-test5-2025-1",
          program: "Nursing",
          cycle: "2025/2026",
          createdAt: "2024-07-10",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-15", time: "11:00", type: "intake", notes: "Nursing program suitability check" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-test5-2025-2",
          program: "Physiotherapy",
          cycle: "2025/2026",
          createdAt: "2024-08-15",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-18", time: "13:30", type: "intake", notes: "Physiotherapy practical assessment" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u9",
      name: "Rick Vermeulen",
      email: "test6@saxion.nl",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-test6-2025-1",
          program: "Hotel & Event Management",
          cycle: "2025/2026",
          createdAt: "2024-06-25",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-20", time: "10:30", type: "intake", notes: "Hospitality management assessment" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-test6-2025-2",
          program: "Tourism Management",
          cycle: "2025/2026",
          createdAt: "2024-07-30",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-22", time: "15:00", type: "intake", notes: "Tourism sector motivation interview" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u10",
      name: "Maud Jongbloed",
      email: "test7@saxion.nl",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-test7-2025-1",
          program: "Architecture",
          cycle: "2025/2026",
          createdAt: "2024-05-18",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-25", time: "09:00", type: "intake", notes: "Architecture portfolio review" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-test7-2025-2",
          program: "Civil Engineering",
          cycle: "2025/2026",
          createdAt: "2024-06-10",
          status: "New",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "2025-02-28", time: "14:00", type: "intake", notes: "Civil engineering technical interview" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
  ],
};

// --- Storage key ---
export const STORAGE_KEY = "saxion-intake-poc";