// --- Simple i18n dictionary ---
export const DICT = {
  en: {
    appTitle: "Saxion Intake – Proof of Concept",
    welcome: "Welcome",
    chooseUser: "Choose a demo user",
    email: "Email",
    password: "Password",
    login: "Login",
    logout: "Logout",
    start: "Start",
    resume: "Resume",
    applications: "Applications",
    archives: "Archives (older than 2 years)",
    runArchival: "Run archival now",
    downloadData: "Download JSON",
    privacy: "Privacy Policy",
    language: "Language",
    local: "Local",
    international: "International",
    program: "Programme",
    cycle: "Cycle",
    status: "Status",
    created: "Created",
    archived: "Archived",
    inProgress: "In progress",
    new: "New",
    submitted: "Submitted",
    resultPublished: "Result published",
    uploadDocuments: "Upload Documents",
    assignment: "Assignment",
    appointment: "Appointment",
    interview: "Interview",
    result: "Result",
    docHint: "Upload study‑related documents (passport, diploma, transcript).",
    upload: "Upload",
    noDocs: "No documents yet.",
    yourDocs: "Your documents",
    submitAssignment: "Submit assignment",
    assignmentHint: "Paste your motivation or upload a PDF.",
    selectDate: "Select date",
    selectTime: "Select time",
    meetingType: "Meeting type",
    intake: "Intake",
    meetGreet: "Meet & Greet",
    notes: "Notes",
    save: "Save",
    interviewMode: "Interview mode",
    online: "Online",
    onCampus: "On campus",
    videoLink: "Video link",
    publishResult: "Publish result",
    unpublishResult: "Unpublish result",
    decision: "Decision",
    admit: "Admit",
    conditional: "Conditional",
    reject: "Reject",
    publishedAt: "Published at",
    noResult: "No published result yet.",
    markAllDone: "Mark steps complete",
    back: "Back",
    startOrResume: "Start / Resume",
    multiApplicationsNote:
      "You can maintain multiple applications; use Start/Resume to continue.",
    profile: "Profile",
    manageYourProfile: "Manage your profile information",
    personalInformation: "Personal Information",
    fullName: "Full Name",
    enterFullName: "Enter your full name",
    enterEmail: "Enter your email address",
    role: "Role",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    applicationStatistics: "Application Statistics",
    totalApplications: "Total Applications",
    completedApplications: "Completed Applications",
    inProgressApplications: "In Progress Applications",
    locationOfHome: "Location of Home",
    enterLocationOfHome: "Enter your home location",
    dateOfBirth: "Date of Birth",
    enterDateOfBirth: "Enter your date of birth",
    profileIncomplete: "Profile Incomplete",
    completeProfileFirst: "You first need to complete your profile before doing something else.",
    completeProfile: "Complete Profile",
    notSpecified: "Not specified",
  },
  nl: {
    appTitle: "Saxion Intake – Proof of Concept",
    welcome: "Welkom",
    chooseUser: "Kies een demo‑gebruiker",
    email: "E‑mail",
    password: "Wachtwoord",
    login: "Inloggen",
    logout: "Uitloggen",
    start: "Start",
    resume: "Hervatten",
    applications: "Aanvragen",
    archives: "Archief (ouder dan 2 jaar)",
    runArchival: "Archivering uitvoeren",
    downloadData: "JSON downloaden",
    privacy: "Privacyverklaring",
    language: "Taal",
    local: "Nationaal",
    international: "Internationaal",
    program: "Opleiding",
    cycle: "Cohort",
    status: "Status",
    created: "Aangemaakt",
    archived: "Gearchiveerd",
    inProgress: "Bezig",
    new: "Nieuw",
    submitted: "Ingediend",
    resultPublished: "Resultaat gepubliceerd",
    uploadDocuments: "Documenten uploaden",
    assignment: "Opdracht",
    appointment: "Afspraak",
    interview: "Interview",
    result: "Resultaat",
    docHint: "Upload studie‑documenten (paspoort, diploma, cijferlijst).",
    upload: "Uploaden",
    noDocs: "Nog geen documenten.",
    yourDocs: "Jouw documenten",
    submitAssignment: "Opdracht indienen",
    assignmentHint: "Plak je motivatie of upload een PDF.",
    selectDate: "Kies datum",
    selectTime: "Kies tijd",
    meetingType: "Afspraaktype",
    intake: "Intake",
    meetGreet: "Meet & Greet",
    notes: "Notities",
    save: "Opslaan",
    interviewMode: "Interviewmodus",
    online: "Online",
    onCampus: "Op locatie",
    videoLink: "Videolink",
    publishResult: "Resultaat publiceren",
    unpublishResult: "Publicatie ongedaan maken",
    decision: "Beslissing",
    admit: "Toelaten",
    conditional: "Voorwaardelijk",
    reject: "Afwijzen",
    publishedAt: "Gepubliceerd op",
    noResult: "Nog geen gepubliceerd resultaat.",
    markAllDone: "Markeer stappen als voltooid",
    back: "Terug",
    startOrResume: "Start / Hervat",
    multiApplicationsNote:
      "Je kunt meerdere aanvragen beheren; gebruik Start/Hervat om verder te gaan.",
    profile: "Profiel",
    manageYourProfile: "Beheer je profielinformatie",
    personalInformation: "Persoonlijke Informatie",
    fullName: "Volledige Naam",
    enterFullName: "Voer je volledige naam in",
    enterEmail: "Voer je e-mailadres in",
    role: "Rol",
    editProfile: "Profiel Bewerken",
    saveChanges: "Wijzigingen Opslaan",
    cancel: "Annuleren",
    applicationStatistics: "Aanvraagstatistieken",
    totalApplications: "Totaal Aanvragen",
    completedApplications: "Voltooide Aanvragen",
    inProgressApplications: "Aanvragen in Uitvoering",
    locationOfHome: "Locatie van Thuis",
    enterLocationOfHome: "Voer je thuislocatie in",
    dateOfBirth: "Geboortedatum",
    enterDateOfBirth: "Voer je geboortedatum in",
    profileIncomplete: "Profiel Onvolledig",
    completeProfileFirst: "Je moet eerst je profiel voltooien voordat je iets anders kunt doen.",
    completeProfile: "Profiel Voltooien",
    notSpecified: "Niet opgegeven",
  },
};

// --- Demo JSON data bootstrap ---
export const DEMO_JSON = {
  users: [
    {
      id: "u1",
      name: "Alex Jansen",
      email: "alex@saxion-demo.nl",
      password: "demo",
      role: "student",
      locale: "nl",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-nl-2023",
          program: "HBO-ICT",
          cycle: "2023/2024",
          createdAt: "2023-05-20",
          status: "inProgress",
          isInternational: false,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "", time: "", type: "intake", notes: "" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
        {
          id: "app-old-2021",
          program: "Creative Media",
          cycle: "2021/2022",
          createdAt: "2021-03-10",
          status: "submitted",
          isInternational: false,
          archived: false,
          steps: {
            documents: [
              {
                id: "d1",
                label: "Diploma.pdf",
                filename: "Diploma.pdf",
                size: 120000,
                mime: "application/pdf",
                uploadedAt: "2021-03-12",
              },
            ],
            assignment: {
              text: "Portfolio link included.",
              file: null,
              submittedAt: "2021-03-15",
            },
            appointment: {
              date: "2021-03-20",
              time: "10:00",
              type: "intake",
              notes: "",
            },
            interview: {
              date: "2021-03-25",
              time: "09:30",
              mode: "online",
              link: "https://meet.example/abc",
            },
            result: {
              published: true,
              decision: "admit",
              publishedAt: "2021-04-10",
              notes: "Congrats!",
            },
          },
        },
      ],
    },
    {
      id: "u2",
      name: "Chidinma Okoro",
      email: "chidinma@saxion-demo.ng",
      password: "demo",
      role: "student",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [
        {
          id: "app-int-2025",
          program: "Applied Computer Science (English)",
          cycle: "2025/2026",
          createdAt: "2025-06-01",
          status: "new",
          isInternational: true,
          archived: false,
          steps: {
            documents: [],
            assignment: { text: "", file: null, submittedAt: null },
            appointment: { date: "", time: "", type: "meet&greet", notes: "" },
            interview: { date: "", time: "", mode: "online", link: "" },
            result: {
              published: false,
              decision: null,
              publishedAt: null,
              notes: "",
            },
          },
        },
      ],
    },
    {
      id: "u3",
      name: "Staff Demo",
      email: "staff@saxion-demo.edu",
      password: "demo",
      role: "staff",
      locale: "en",
      locationOfHome: "",
      dateOfBirth: "",
      applications: [],
    },
  ],
};

// --- Storage key ---
export const STORAGE_KEY = "saxion-intake-poc"; 